swagger: '2.0'
info:
  description: Des
  version: 1.0.0
  title: Swagger Petstore
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://127.0.0.1:5000/api
    description: Dev Server
paths:
  /api/login{email_}/{password}:
    get:
      description:
        login api
      parameters:
       - name: email_
         in: path
         description: login user
         schema:
            type: string
            minimum: 2 
            example: bagwan.akib@gmail.com
       - name: password
         in: path
         description: login passward
         schema:
            type: string
            minimum: 2 
            example: 123
      responses:
        200:
          description: success loging
          content:
            application/json:
              schema:
              type: array
              items:
                properties:
                  status:
                    type: boolean
                    example: True
                    
      